apiVersion: 1

datasources:
  - name: AirflowDB
    type: postgres
    url: postgres:5432
    database: airflow
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: "disable"
    isDefault: true
